from __future__ import annotations

import argparse
import sys
from pathlib import Path

module_file = globals().get("__file__")
SKILL_DIR = Path(module_file).resolve().parent.parent if module_file else Path.cwd().resolve()
sys.path.insert(0, str(SKILL_DIR))

from lib.conversion import load_manifest
from lib.obsidian_import import (
    copy_all_assets,
    copy_referenced_assets,
    extract_markdown_image_asset_names,
    join_target_root,
    plan_import_targets,
    resolve_vault_path,
    iter_note_content,
    iter_rewritten_markdown_image_embeds,
    verify_note_assets,
    write_obsidian_note_iter,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Import converted MinerU notes into Obsidian")
    parser.add_argument("--manifest", required=True, help="Manifest JSON generated by convert_recursive.py")
    parser.add_argument("--target-root", required=True, help="Vault subpath used as the deterministic import root")
    parser.add_argument("--vault", default="", help="Optional Obsidian vault name override")
    parser.add_argument(
        "--preserve-assets",
        dest="preserve_assets",
        action="store_true",
        default=True,
        help="Preserve extracted assets inside the vault images/ directory (enabled by default)",
    )
    parser.add_argument(
        "--no-preserve-assets",
        dest="preserve_assets",
        action="store_false",
        help=argparse.SUPPRESS,
    )
    parser.add_argument("--chunk-size", type=int, default=3000, help="Max content chunk size for Obsidian writes")
    return parser


def build_target_plan(manifest_entries: list[dict], target_root: str) -> dict[str, dict[str, str]]:
    fallback = plan_import_targets(manifest_entries, target_root=target_root)
    plan: dict[str, dict[str, str]] = {}

    for entry in manifest_entries:
        source_file = str(entry["source_file"])
        target_note_rel_path = str(entry.get("target_note_rel_path") or "")
        target_images_rel_path = str(entry.get("target_images_rel_path") or "")

        if target_note_rel_path and target_images_rel_path:
            target_note_path = join_target_root(target_root, target_note_rel_path)
            target_images_dir = join_target_root(target_root, target_images_rel_path)
        else:
            fallback_target = fallback[source_file]
            target_note_path = fallback_target.target_note_path
            target_images_dir = fallback_target.target_images_dir

        plan[source_file] = {
            "target_note_path": target_note_path,
            "target_images_dir": target_images_dir,
        }

    return plan


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    manifest = load_manifest(Path(args.manifest))
    manifest_entries = manifest.get("entries", [])
    if not manifest_entries:
        raise RuntimeError("Manifest does not contain any conversion entries")

    target_plan = build_target_plan(manifest_entries, args.target_root)
    vault_root = resolve_vault_path(args.vault)

    seen_targets: set[str] = set()
    for source_file, target in target_plan.items():
        target_note_path = target["target_note_path"]
        if target_note_path in seen_targets:
            raise RuntimeError(f"Duplicate target path in import plan: {target_note_path}")
        seen_targets.add(target_note_path)

        entry = next(item for item in manifest_entries if item["source_file"] == source_file)
        markdown_path = Path(entry["markdown_path"])
        asset_names = extract_markdown_image_asset_names(markdown_path)
        # Note content is streamed and may be written in multiple attempts (with
        # smaller chunks) if Obsidian CLI is flaky. Keep this as a factory so we
        # can retry deterministically.
        def make_content_parts():
            return iter_note_content(iter_rewritten_markdown_image_embeds(markdown_path))

        target_images_dir = Path(vault_root) / target["target_images_dir"]
        assets_dir = Path(entry["assets_dir"]) if entry.get("assets_dir") else None

        if args.preserve_assets and assets_dir is not None and assets_dir.exists():
            copy_all_assets(assets_dir, target_images_dir)

        if asset_names:
            copy_referenced_assets(assets_dir, asset_names, target_images_dir)

        chunk_sizes = [args.chunk_size]
        if args.chunk_size > 1000:
            chunk_sizes.append(1000)
        if args.chunk_size > 500:
            chunk_sizes.append(500)

        last_error: Exception | None = None
        for chunk_size in chunk_sizes:
            try:
                write_obsidian_note_iter(
                    target_path=target_note_path,
                    content_parts=make_content_parts(),
                    vault=args.vault,
                    chunk_size=chunk_size,
                    vault_root=vault_root,
                )
                last_error = None
                break
            except RuntimeError as exc:
                last_error = exc
        if last_error is not None:
            raise last_error

        if asset_names:
            target_note_fs_path = Path(vault_root) / target_note_path
            verify_note_assets(target_note_fs_path, asset_names, target_images_dir)

    print(f"Imported {len(manifest_entries)} notes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
